### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by newfinal100** [perkss/tinklj#15]
Hello! I'd like to contribute to your project by designing a logo for it. Let me know if you'd want that too, as well as if there are any specific things you'd want this logo to represent, if you don't have any I'll just implement my own ideas. Looking forward to hearing from you :)

**Comment by perkss** [comment]
@newfinal100 yes please go for it! Let us see what you have got no specifics from me.

**Comment by newfinal100** [comment]
Okay so I tried to incorporate all the characteristics of your project into one logo-mark, from which I made these four variations. Let me know what you think of it, for an example if you like it but would want some changes/improvements done to it, or you want a completely different look to this logo-mark. And of course, after we are done with this part I'll move on to the logotype part and typography :)

![tinkle four-01](https://user-images.githubusercontent.com/49202520/55684618-58e0eb80-594d-11e9-9778-c14617621347.jpg)

**Comment by perkss** [comment]
So of the bottom row I really like the First one or the Third one. Thanks so much they all look so awesome. Keep it going!

**Comment by newfinal100** [comment]
I'm really glad you liked them! :)

So I created some logo-type variations with the two logo-marks you liked. Let me know which version you like the most and if there are any changes you'd want me to make!

![Tinklj typeface variations](https://user-images.githubusercontent.com/49202520/55685090-add33080-5952-11e9-9622-2aea9626075a.png)

**Comment by perkss** [comment]
I think I like the first one top left. Or the last one bottom right of the two tones. Tricky they really are good. Can you share those and I can see what they look like on the README, or can you update and insert them into the README and PR.

**Comment by newfinal100** [comment]
Of course I'll send you both of them! I'll just need a few minutes to upload them on Google Drive and send you the link :)

**Comment by newfinal100** [comment]
https://drive.google.com/drive/folders/1XDRmZfeT-yN9q8NXCCtm7K9fL7mWstbB?usp=sharing

**Comment by newfinal100** [comment]
I deleted the previous files cause I noticed some minor mistakes in them, now I uploaded the improved versions on the same link. If you already downloaded the previous ones, you can delete them and use these instead :)

**Comment by perkss** [comment]
Could you add the padding back to the (2) files they made the banner shape better for the README

**Comment by newfinal100** [comment]
Sure! I added those too

**Comment by perkss** [comment]
Thanks so much please check it out here: https://github.com/perkss/tinklj/tree/Tinklj-logo

If you are happy please approve and merge the PR or I will. https://github.com/perkss/tinklj/pull/19

**Comment by perkss** [comment]
@newfinal100 thanks so much for that looks so good!!

**Comment by newfinal100** [comment]
I'm really glad you liked the logo! :) If there's anything else you may need let me know!
